### ISSUE TITLE
kafka  not run

### ISSUE THREAD

**Issue by yinhejianke** [sitewhere/sitewhere-k8s#157]
**Describe the bug**

**Provide Information**
Output of `helm version`:

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GitCommit:"224059d", GitTreeState:"", BuildDate:"2020-02-15T00:35:19Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GitCommit:"224059d", GitTreeState:"", BuildDate:"2020-02-17T00:08:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Output of `helm ls sitewhere`

NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
sitewhere       1               Mon Aug 10 20:31:48 2020        DEPLOYED        sitewhere-0.2.9 2.2             default  

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k8s 1.14
SiteWhere App Version:
2.1
SiteWhere Chart Version:

**To Reproduce**

**Expected behavior**

[2020-08-10 12:49:13,520] WARN [SocketServer brokerId=0] Unexpected error from /172.20.1.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:448)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:398)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
        at kafka.network.Processor.poll(SocketServer.scala:893)
        at kafka.network.Processor.run(SocketServer.scala:792)
        at java.lang.Thread.run(Thread.java:748)
**Additional context**

[2020-08-10 12:49:13,520] WARN [SocketServer brokerId=0] Unexpected error from /172.20.1.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:448)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:398)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
        at kafka.network.Processor.poll(SocketServer.scala:893)
        at kafka.network.Processor.run(SocketServer.scala:792)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @yinhejianke,
Can you provide more detailed description of what the error is?
