### ISSUE TITLE
Failed to deploy sitewhere 2.1.1 (Some pods report "No sitewhere.config.k8s.name value",  others is pending for unbound immediate PersistentVolumeClaims)

### ISSUE THREAD

**Issue by jiezhuangcn** [sitewhere/sitewhere-k8s#184]
**Describe the bug**
I tried to deploy sitewhere according to the document  (https://sitewhere.io/docs/2.1.0/deployment/)， but met some errors. 

![123](https://user-images.githubusercontent.com/3940604/181439242-edee22de-3cb1-46b4-886f-cebd623c6bdd.png)

I checked the log of pods in crashloopbackoff status, all errors are same, as follow:

```
2022-07-28 06:49:55,944 ERROR [io.qua.application] (main) Failed to start application (with profile prod): javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: sitewhere.config.k8s.name
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37) at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy_0(ConfigBuildStep$validateConfigProperties1249763973.zig:192) at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy(ConfigBuildStep$validateConfigProperties1249763973.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:358)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:92)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

For those pods in pending status, also have same warning:

`Warning  FailedScheduling  3s (x26 over 25m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`

[](url)

**Provide Information**
Output of `helm version`:
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

Output of `helm ls sitewhere`
sitewhere    	default  	1       	2022-07-28 14:25:17.502448193 +0800 CST	deployed	sitewhere-0.2.9	2.1.1     

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube (On Clound VM)

SiteWhere App Version:
2.1.1

SiteWhere Chart Version:
0.2.8
(From https://github.com/sitewhere/sitewhere-k8s/releases/tag/v0.2.8)

**To Reproduce**
I installed minikube on the cloud virtual machine and successfully started it with the --driver=none parameter. 

Next, I installed the helm3.9 which is consistent with k8s version, then installed itsio.
```
istio-system   istio-egressgateway-7cc7b7fc5d-xhdgk              1/1     Running            0                5h58m
istio-system   istio-ingressgateway-7d4b79679b-bg2sw             1/1     Running            0                5h58m
istio-system   istiod-7cf4b49f6d-qgvjj                           1/1     Running            0                5h59m
```

I didn't install metallb because I intend to use port forward to expose service. 

Instead of installing rook, I use hostpath as storage.

The only difference from the document,  is helm -name option.  It cannot be recognized, because helm3 no longer supports this helm2 option, so the final install instruction is

`helm install sitewhere --set persistence storageClass=hostpath ./sitewhere。`

**Expected behavior**
Successfully deployed.

**Additional context**
OS: CentOS 7.2
Docker: 20.10.17

**Comment by gzkahjl** [comment]
Have you solved it ？

**Comment by jiezhuangcn** [comment]
> Have you solved it ？

Not yet.

**Comment by gzkahjl** [comment]
> > Have you solved it ？
> 
> Not yet.

 I also encountered such problems 。

**Comment by duowen1** [comment]
Me too

**Comment by outbackdingo** [comment]
seems dead this is a failure to deploy on both docker and k8s for us also.....
