### ISSUE TITLE
Getting request failed with code 500 when trying login with default username/password

### ISSUE THREAD

**Issue by cristichiru** [sitewhere/sitewhere-k8s#42]
**Describe the bug**
On a fresh deployment, cannot access Administration dashboard because of failed login with default credentials: `admin/password`

**Provide Information**
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Output of `helm ls sitewhere`
* Not installed using Tiller, just used helm to generate k8s artefacts then loaded them

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
- None, private cloud on bare metal, Kubernetes deployed with kubespray

SiteWhere App Version:
- docker.io/sitewhere/service-web-rest:2.0.7

SiteWhere Chart Version:
- Latest `sitewhere` from https://sitewhere.io/helm-charts

**To Reproduce**
1. Expose `sitewhere-web-rest-http` service to externalIP
2. Using the Sitewhere administration client, try to login using `http://externalip:8080`
3. Alternatively, on one of the nodes:
`curl -u admin:password http://sitewhere-web-rest-http.sitewhere:8080/sitewhere/authapi/jwt`

**Expected behavior**
Authenticate successfully and see the dashboard

**Additional context**
Log from the `sitewhere-web-rest` pod:
```
2019-05-03 00:56:48.644  INFO 1 --- [croservice Main] c.s.m.zookeeper.ZookeeperManager         : Waiting for Zookeeper to become available...
2019-05-03 00:57:03.668 ERROR 1 --- [nio-8080-exec-3] c.s.w.s.SiteWhereAuthenticationProvider  : Authentication exception.

java.lang.NullPointerException: null
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.validateUserManagement(SiteWhereAuthenticationProvider.java:145) [classes!/:na]
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticateBasicAuth(SiteWhereAuthenticationProvider.java:85) [classes!/:na]
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticate(SiteWhereAuthenticationProvider.java:57) [classes!/:na]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) [spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) [spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:180) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-05-03 00:57:03.669 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[.[sitewhereAuthInterface] : Servlet.service() for servlet [sitewhereAuthInterface] in context with path [/sitewhere] threw exception

java.lang.NullPointerException: null
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.validateUserManagement(SiteWhereAuthenticationProvider.java:145) ~[classes!/:na]
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticateBasicAuth(SiteWhereAuthenticationProvider.java:85) ~[classes!/:na]
        at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticate(SiteWhereAuthenticationProvider.java:57) ~[classes!/:na]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) ~[spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:180) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-05-03 00:57:48.644  INFO 1 --- [croservice Main] c.s.m.zookeeper.ZookeeperManager         : Waiting for Zookeeper to become available...
```

**Comment by cristichiru** [comment]
![image](https://user-images.githubusercontent.com/28685998/57115955-b0ab2080-6d5a-11e9-9f98-f852573a0a95.png)

**Comment by cristichiru** [comment]
Not sure if related:

1. Pod `test-topic-create-consume-produce` terminated with exception, but it make sense since zookeeper pods were slow to start and there was no initContainer to wait for them
```
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:230)
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
	at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:226)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1587)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:57)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
```
2. Pod `ui-test-frp2d` failed as well:
```
1..1
not ok 1 Testing Consul cluster has quorum
```

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @cristichiru, thanks for reporting the issue.

From the logs you provided it seems that SiteWhere hasn't started yet 

```
2019-05-03 00:56:48.644  INFO 1 --- [croservice Main] c.s.m.zookeeper.ZookeeperManager         : Waiting for Zookeeper to become available...
```
Do you see a message like this one?

```
********************************************************************************
* Web/REST Microservice                                                        *
* Startup time: 124686ms                                                       *
********************************************************************************
```

**Comment by derekadams** [comment]
Yes, this seems like a case where the user management microservice has not started successfully, but the REST API is still trying to access it. It's a bug because the Web/REST microservice should not have a connection to an instance of a microservice that isn't successfully started (should return a 503/service unavailable status). Can you provide logs from the user management microservice?

**Comment by derekadams** [comment]
Note that once this bug is reproduced, we may move this to an issue on SiteWhere core as it's probably not related to K8s.

**Comment by cristichiru** [comment]
> Note that once this bug is reproduced, we may move this to an issue on SiteWhere core as it's probably not related to K8s.

No problem, whatever is needed

**Comment by cristichiru** [comment]
## sitewhere-user-management logs
```
2019-05-03 00:50:45.399 ERROR 1 --- [croservice Main] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up

java.net.UnknownHostException: revo-sitewhere-zookeeper: Name does not resolve
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_201]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_201]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_201]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[na:1.8.0_201]
        at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_201]
        at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_201]
```

It seems it tries to access "prefix-sitewhere-zookeeper", however the actual service is just **prefix-zookeeper** as is generated by the dependency chart

In [_microserviceEnvValues.tpl](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere/templates/_microserviceEnvValues.tpl) there is:
```yaml
- name: "sitewhere.zookeeper.host"
  value: "{{ include "sitewhere.zookeeper.host" . }}"
```
that is calculated in [_subcharts.tpl](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere/templates/_subcharts.tpl#L4) seems to be using **sitewhere.fullname** 
```yaml
{{- define "sitewhere.zookeeper.host" -}}
{{- if (index .Values "sitewhere-infra-core" "kafka" "enabled") -}}
-----> {{ include "sitewhere.fullname" . }}-zookeeper
{{- else -}}
{{- index .Values "sitewhere-infra-core" "kafka" "zookeeper_host" -}}
```

**Comment by jorgevillaverde-sitewhere** [comment]
ok, this is definitely a bug.

**Comment by cristichiru** [comment]
One solution is to use **nameOverride** for subcharts in primary `values.yml`:
```yaml
sitewhere-infra-core:
  consul:
    nameOverride: sitewhere-kafka
    StorageClass: rook-ceph-block
  kafka:
    nameOverride: sitewhere-kafka
    configurationOverrides:
      "num.partitions": 3
      "default.replication.factor": 3
      "min.insync.replicas": 2
      "leader.imbalance.check.interval.seconds": 30
    persistence:
      storageClass: rook-ceph-block
    external:
      enabled: false
    zookeeper:
      nameOverride: sitewhere-zookeeper
      service:
        type: NodePort
      persistence:
        storageClass: rook-ceph-block


sitewhere-infra-database:
  mongodb:
    nameOverride: sitewhere-kafka
    persistence:
      storageClass: rook-ceph-block
  cassandra:
    nameOverride: sitewhere-kafka
    persistence:
      storageClass: rook-ceph-block
  influxdb:
    nameOverride: sitewhere-kafka
    persistence:
      storageClass: rook-ceph-block
```

**Comment by jorgevillaverde-sitewhere** [comment]
@cristichiru, I added some helper functions to override the name of the sub-chart.

I test it using `prefix` (or other name rather than `sitewheer`)

```
kubectl get svc
NAME                                       TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                            AGE
kubernetes                                 ClusterIP      10.96.0.1        <none>        443/TCP                                                                            9d
prefix-consul                              ClusterIP      None             <none>        8500/TCP,8400/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   1m
prefix-consul-ui                           NodePort       10.111.232.240   <none>        8500:32427/TCP                                                                     1m
prefix-kafka                               ClusterIP      10.102.206.238   <none>        9092/TCP                                                                           1m
prefix-kafka-headless                      ClusterIP      None             <none>        9092/TCP                                                                           1m
prefix-mongodb                             ClusterIP      10.106.135.160   <none>        27017/TCP                                                                          1m
prefix-mongodb-headless                    ClusterIP      None             <none>        27017/TCP                                                                          1m
prefix-sitewhere-asset-management-svc      ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-batch-operations-svc      ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-command-delivery-svc      ClusterIP      10.103.233.13    <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-device-management-svc     ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-device-registration-svc   ClusterIP      10.108.139.178   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-device-state-svc          ClusterIP      10.97.60.41      <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-event-management-svc      ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-event-search-svc          ClusterIP      10.107.127.136   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-event-sources-svc         ClusterIP      10.101.154.133   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-inbound-processing-svc    ClusterIP      10.110.26.89     <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-instance-management-svc   ClusterIP      10.108.139.208   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-jaeger-svc                ClusterIP      10.105.219.32    <none>        9411/TCP,16686/TCP                                                                 1m
prefix-sitewhere-label-generation-svc      ClusterIP      10.108.138.30    <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-mosquitto-svc             LoadBalancer   10.108.85.35     localhost     1883:30333/TCP                                                                     1m
prefix-sitewhere-outbound-connectors-svc   ClusterIP      10.109.133.201   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-rule-processing-svc       ClusterIP      10.100.196.198   <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-schedule-management-svc   ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-streaming-media-svc       ClusterIP      10.111.113.65    <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-tenant-management-svc     ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-user-management-svc       ClusterIP      None             <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-web-rest-grpc             ClusterIP      10.98.146.144    <none>        9000/TCP,9001/TCP                                                                  1m
prefix-sitewhere-web-rest-http             LoadBalancer   10.102.251.157   localhost     8080:30516/TCP                                                                     1m
prefix-zookeeper                           NodePort       10.109.204.72    <none>        2181:32116/TCP                                                                     1m
prefix-zookeeper-headless                  ClusterIP      None             <none>        2181/TCP,3888/TCP,2888/TCP                                                         1m```

It resolves ok

```
2019-05-03 23:08:00.367  INFO 1 --- [croservice Main] c.s.a.m.AssetManagementMicroservice      : 

********************************************************************************
* Asset Management Microservice                                                *
* Version: 2.0.6.9ed3979                                                       *
* Git Revision: 9ed3979b07d56d23ae9db5dc34efdbf1da5b51cb                       *
* Build Date: 20190404205936                                                   *
* Hostname: 10.1.2.146                                                         *
********************************************************************************

2019-05-03 23:08:01.346  INFO 1 --- [croservice Main] c.s.a.m.AssetManagementMicroservice      : Sending state update for lifecycle status change (Initializing).
2019-05-03 23:08:01.356  WARN 1 --- [croservice Main] c.s.a.m.AssetManagementMicroservice      : Unable to report state. Waiting on Kafka producer to become available.
2019-05-03 23:08:01.457  INFO 1 --- [croservice Main] c.s.a.m.AssetManagementMicroservice      : Metrics reporting is disabled.
2019-05-03 23:08:01.606  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (11.0%) Initialize ConsulServiceDiscoveryProvider
2019-05-03 23:08:01.613  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (22.0%) Start ConsulServiceDiscoveryProvider
2019-05-03 23:08:01.616  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (33.0%) Initialize ScriptTemplateManager
2019-05-03 23:08:01.617  INFO 1 --- [croservice Main] c.s.m.scripting.ScriptTemplateManager    : Microservice does not contain any script templates.
2019-05-03 23:08:01.618  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (44.0%) Start ScriptTemplateManager
2019-05-03 23:08:02.523  INFO 1 --- [           main] c.s.asset.AssetManagementApplication     : Started AssetManagementApplication in 22.782 seconds (JVM running for 29.415)
2019-05-03 23:08:05.345  INFO 1 --- [croservice Main] c.s.m.zookeeper.ZookeeperManager         : Waiting for Zookeeper to become available...
2019-05-03 23:09:05.346  INFO 1 --- [croservice Main] c.s.m.zookeeper.ZookeeperManager         : Waiting for Zookeeper to become available...
2019-05-03 23:09:09.966  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (55.0%) Initialize ZookeeperManager
2019-05-03 23:09:11.888  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (66.0%) Initialize MicroserviceManagementGrpcServer
2019-05-03 23:09:12.616  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (77.0%) Start MicroserviceManagementGrpcServer
2019-05-03 23:09:12.616  INFO 1 --- [croservice Main] c.s.s.l.LifecycleProgressMonitor         : [Initialize Asset Management]: (88.0%) Initialize MicroserviceStateUpdatesKafkaProducer
2019-05-03 23:09:12.625  INFO 1 --- [croservice Main] .s.MicroserviceStateUpdatesKafkaProducer : Producer connecting to Kafka: prefix-kafka:9092
2019-05-03 23:09:12.626  INFO 1 --- [croservice Main] .s.MicroserviceStateUpdatesKafkaProducer : Will be producing messages for: sitewhere.prefix.global.microservice-state-updates
2019-05-03 23:09:14.958  INFO 1 --- [croservice Main] .s.MicroserviceStateUpdatesKafkaProducer : Attempting to connect to Kafka...
```

Let me know if it works for you.

**Comment by cristichiru** [comment]
Works as expected, I can access the administration dashboard now, thanks!
Probably it's safe to do a release of the helm chart version 0.1.8

Thanks!
